export const property_list = [
  {
    name: "House 1",
    price: 129,
    address: "22 Green Valley, Highland Lake, FL",
    beds: 3,
    bathrooms: 3,
    area: "5x7",
    type: "house",
    location: "New York",
    image: "house1.jpg",
    from: 4,
    to: 18,
  },
  {
    name: "House 2",
    price: 399,
    address: "909 Woodland St. Michigan, IN",
    beds: 2,
    bathrooms: 1,
    area: "8x10",
    type: "house",
    location: "California",
    image: "house2.jpg",
    from: 6,
    to: 9,
  },
  {
    name: "House 3",
    price: 499,
    address: "56 Lake Sevilla, Palm Harbor, TX",
    beds: 4,
    bathrooms: 2,
    area: "6x7.5",
    type: "house",
    location: "New York",
    image: "house3.jpg",
    from: 5,
    to: 12,
  },
  {
    name: "House 4",
    price: 519,
    address: "909 Woodland St. Michigan, IN",
    beds: 2,
    bathrooms: 1,
    area: "8x10",
    type: "house",
    location: "California",
    image: "house4.jpg",
    from: 8,
    to: 14,
  },
  {
    name: "House 5",
    price: 1999,
    address: "909 Woodland St. Michigan, IN",
    beds: 4,
    bathrooms: 3,
    area: "8x10",
    type: "house",
    location: "New York",
    image: "house5.jpg",
    from: 7,
    to: 11,
  },
  {
    name: "House 6",
    price: 2299,
    address: "909 Woodland St. Michigan, IN",
    beds: 2,
    bathrooms: 1,
    area: "8x10",
    type: "house",
    location: "California",
    image: "house6.jpg",
    from: 13,
    to: 18,
  },
  {
    name: "House 7",
    price: 2600,
    address: "909 Woodland St. Michigan, IN",
    beds: 2,
    bathrooms: 1,
    area: "8x10",
    type: "house",
    location: "New York",
    image: "house7.jpg",
    from: 7,
    to: 14,
  },
  {
    name: "House 8",
    price: 3300,
    address: "909 Woodland St. Michigan, IN",
    beds: 2,
    bathrooms: 1,
    area: "8x10",
    type: "house",
    location: "California",
    image: "house1.jpg",
    from: 4,
    to: 10,
  },
  {
    name: "House 9",
    price: 4799,
    address: "909 Woodland St. Michigan, IN",
    beds: 2,
    bathrooms: 1,
    area: "8x10",
    type: "house",
    location: "New York",
    image: "house2.jpg",
    from: 6,
    to: 12,
  },
  {
    name: "House 10",
    price: 5100,
    address: "909 Woodland St. Michigan, IN",
    beds: 2,
    bathrooms: 1,
    area: "8x10",
    type: "house",
    location: "California",
    image: "house3.jpg",
    from: 9,
    to: 15,
  },
  {
    name: "House 11",
    price: 6800,
    address: "909 Woodland St. Michigan, IN",
    beds: 2,
    bathrooms: 1,
    area: "8x10",
    type: "house",
    location: "New York",
    image: "house4.jpg",
    from: 14,
    to: 18,
  },
  {
    name: "House 12",
    price: 9199,
    address: "909 Woodland St. Michigan, IN",
    beds: 2,
    bathrooms: 1,
    area: "8x10",
    type: "house",
    location: "California",
    image: "house5.jpg",
    from: 12,
    to: 17,
  },
  {
    name: "House 13",
    price: 11000,
    address: "909 Woodland St. Michigan, IN",
    beds: 2,
    bathrooms: 1,
    area: "8x10",
    type: "house",
    location: "New York",
    image: "house6.jpg",
    from: 13,
    to: 18,
  },
  {
    name: "House 14",
    price: 13999,
    address: "909 Woodland St. Michigan, IN",
    beds: 2,
    bathrooms: 1,
    area: "8x10",
    type: "house",
    location: "California",
    image: "house7.jpg",
    from: 9,
    to: 15,
  },
  {
    name: "House 15",
    price: 17419,
    address: "909 Woodland St. Michigan, IN",
    beds: 2,
    bathrooms: 1,
    area: "8x10",
    type: "house",
    location: "New York",
    image: "house1.jpg",
    from: 4,
    to: 12,
  },
  {
    name: "Flat 1",
    price: 1295,
    address: "909 Woodland St. Michigan, IN",
    beds: 2,
    bathrooms: 1,
    area: "8x10",
    type: "flat",
    location: "California",
    image: "flat1.jpg",
    from: 4,
    to: 15,
  },
  {
    name: "Flat 2",
    price: 2295,
    address: "909 Woodland St. Michigan, IN",
    beds: 2,
    bathrooms: 1,
    area: "8x10",
    type: "flat",
    location: "New York",
    image: "flat2.jpg",
    from: 4,
    to: 18,
  },
  {
    name: "Flat 3",
    price: 3799,
    address: "909 Woodland St. Michigan, IN",
    beds: 2,
    bathrooms: 1,
    area: "8x10",
    type: "flat",
    location: "California",
    image: "flat3.jpg",
    from: 8,
    to: 12,
  },
  {
    name: "Flat 4",
    price: 4839,
    address: "909 Woodland St. Michigan, IN",
    beds: 2,
    bathrooms: 1,
    area: "8x10",
    type: "flat",
    location: "New York",
    image: "flat4.jpg",
    from: 5,
    to: 12,
  },
  {
    name: "Flat 5",
    price: 4999,
    address: "909 Woodland St. Michigan, IN",
    beds: 2,
    bathrooms: 1,
    area: "8x10",
    type: "flat",
    location: "California",
    image: "flat5.jpg",
    from: 4,
    to: 18,
  },
  {
    name: "Flat 6",
    price: 5499,
    address: "909 Woodland St. Michigan, IN",
    beds: 2,
    bathrooms: 1,
    area: "8x10",
    type: "flat",
    location: "New York",
    image: "flat6.jpg",
    from: 7,
    to: 15,
  },
  {
    name: "Flat 7",
    price: 6599,
    address: "909 Woodland St. Michigan, IN",
    beds: 2,
    bathrooms: 1,
    area: "8x10",
    type: "flat",
    location: "California",
    image: "flat7.jpg",
    from: 12,
    to: 18,
  },
  {
    name: "Flat 8",
    price: 8299,
    address: "909 Woodland St. Michigan, IN",
    beds: 2,
    bathrooms: 1,
    area: "8x10",
    type: "flat",
    location: "New York",
    image: "flat1.jpg",
    from: 7,
    to: 12,
  },
  {
    name: "Flat 9",
    price: 14599,
    address: "909 Woodland St. Michigan, IN",
    beds: 2,
    bathrooms: 1,
    area: "8x10",
    type: "flat",
    location: "California",
    image: "flat2.jpg",
    from: 11,
    to: 14,
  },
  {
    name: "Flat 10",
    price: 17599,
    address: "909 Woodland St. Michigan, IN",
    beds: 2,
    bathrooms: 1,
    area: "8x10",
    type: "flat",
    location: "New York",
    image: "flat3.jpg",
    from: 6,
    to: 13,
  },
];
